version: "3.8"
services:
  backend:
    build: ../backend
    image: backend:latest # nomeie a imagem da forma que desejar
    ports:
      - "5000:5000"

  frontend:
    build: ../frontend
    image: frontend:latest # nomeie a imagem da forma que desejar
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://backend:5000/api/v1"
      API_BASE_URL: "http://backend:5000/api/v1"
