import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import { Toaster } from "@/components/ui/toaster"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Murabei Library</title>
    </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <NavigationBar />
        {children}
        <Toaster />
        <footer className="bg-white rounded-lg shadow m-4 dark:bg-gray-800 mt-auto">
    <div className="w-full  p-4 md:flex md:items-center md:justify-between">
    
        <p className="text-balance text-center text-sm leading-loose text-muted-foreground md:text-left">
          Built by Ray S. Arruda
        </p>
      </div>
    </footer>
      </body>
    </html>
  );
}
